networks:
  default:
    name: arr
    external: true

services:
  prowlarr: #indexer manager for Sonarr & Radarr
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - $HOME/homelab-data/services-config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr: #movie search agent
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - UMASK=022
    volumes:
      - $HOME/homelab-data/services-config/radarr:/config
      - /mnt/media/library:/library
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: #TV show search agent
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - UMASK=022
    volumes:
      - $HOME/homelab-data/services-config/sonarr:/config
      - /mnt/media/library:/library
    ports:
      - 8989:8989  
    restart: unless-stopped