services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
    volumes:
      - $HOME/homelab-data/services-config/heimdall:/config
    ports:
      - 8080:80
        #- 443:443
    restart: unless-stopped
