services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Etc/Ljubljana
      - PLEX_CLAIM=claim-pEWwEzzcyG9DxxCv_x8A
    volumes:
      - $HOME/homelab-data/services-config/plex:/config
      - $HOME/homelab-data/media:/local-media
      - /mnt/media:/media-dirve
