services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME/homelab-data/services-config/plex:/config
      - $HOME/homelab-data/media/movies:/movies
      - $HOME/homelab-data/media/shows:/tv
      - /mnt/media:/media-dirve
