services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ADVERTISE_IP=http://10.37.30.10:32400/
    # - PLEX_CLAIM=<claimToken>
    volumes:
      - ~/home-lab/plex/db:/config
      - /home/homelab-data/movies:/movies
      - ~/home-lab/homelab-media/shows:/tv
      - /etc/localtime:/etc/localtime:ro
