version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    env_file: 
      - $HOME/services/watchtower/.env
    environment:
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Ljubljana
      - WATCHTOWER_SCHEDULE=0 0 4 */5 * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
