services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp   # plain DNS
      - 53:53/udp   # plain DNS
      # enable if you intend to use AdGuard Home as a DHCP server
      # - 67:67/udp
      # - 68:68/udp
      # - 80:80/tcp

      # enable if you are going to use AdGuard Home's admin panel
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      
      # enable if you are going to run AdGuard Home as a DNS-over-TLS server.
      # - 853:853/tcp
      
      # enable if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these.
      # - 784:784/udp
      # - 853:853/udp
      # - 8853:8853/udp

      # enable if you are going to run AdGuard Home as a DNSCrypt server
      # - 5443:5443/tcp
      # - 5443:5443/udp