version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - $HOME/homelab-data/services-config/postgres:/var/lib/postgresql/data
    env_file:
      -  $HOME/services/postgres/.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8987:8080