version: '3.1'

services:
  postgres-db:
    image: postgres:15
    restart: always
    volumes:
      - $HOME/homelab-data/services-config/postgres:/var/lib/postgresql/data
    env_file:
      -  $HOME/services/postgres/.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80